### ISSUE TITLE
Support for more UI frameworks

### ISSUE THREAD

**Issue by Abrissirba** [Sector43/FabricExplorer#1]
Hi

I just saw your pluralsight course for UI Fabric and really liked your demonstration of this tool and instantly wanted it for other frameworks I use. Do you know of any existing chrome extensions like this for e.g. bootstrap and angular material? Otherwise it would be cool if one could extend this plugin to support multiple frameworks. Happy to help if needed!

**Comment by manndave** [comment]
@Abrissirba:  Thanks, glad you like it.  I'm not aware of anything else like it (doesn't mean they don't exist, I haven't really looked).  If you want to explore extending it to other frameworks, you can fork the code and give it a whirl.  Be aware, though, that I'm planning a major rewrite for this summer that may help with some of that (though I won't be intentionally extending it beyond Fabric myself).

Dave
